version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install flake8
          flake8 calculations.py

  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install pytest
          pytest test_calculations.py

workflows:
  version: 2.1
  myworkflow:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - test:
          requires:
            - lint
