version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          sudo pip install pytest
          pytest test_calculations.py --junit-xml=test-results/pytest.xml
      - store_test_results:
          path: test-results

